### ISSUE TITLE
Could not invoke RCTZegoExpressNativeModule. createEngineWithProfile

### ISSUE THREAD

**Issue by VikasReactNative** [zegoim/zego-express-reactnative-sdk#1]
i don't know what is missing after build it shows the error as shown 

 
![WhatsApp Image 2024-02-27 at 12 15 19 PM](https://github.com/zegoim/zego-express-reactnative-sdk/assets/85869501/5b04583b-e7de-4e69-9d97-fe37004abb4b)

![Screenshot 2024-02-27 at 2 20 56 PM](https://github.com/zegoim/zego-express-reactnative-sdk/assets/85869501/b616c2a9-bdfa-4e42-91f0-1632cd41905c)
### log cat error
 load ZegoExpressSDK native library failed
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libZegoExpressEngine.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at im.zego.zegoexpress.internal.ZegoExpressEngineInternalImpl.<clinit>(Unknown Source:119)
                                                                                                    	at im.zego.zegoexpress.ZegoExpressEngine.setEngineConfig(Unknown Source:0)
                                                                                                    	at im.zego.reactnative.RCTZegoExpressNativeModule.reportPluginInfo(RCTZegoExpressNativeModule.java:225)
                                                                                                    	at im.zego.reactnative.RCTZegoExpressNativeModule.createEngineWithProfile(RCTZegoExpressNativeModule.java:248)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-02-27 14:41:46.969 13177-13335 com.yaamet              com.yaamet                           E  No implementation found for void im.zego.zegoexpress.internal.ZegoExpressEngineJniAPI.setEngineInitConfigToJni(im.zego.zegoexpress.entity.ZegoEngineConfig, java.lang.String, long, java.lang.String) (tried Java_im_zego_zegoexpress_internal_ZegoExpressEngineJniAPI_setEngineInitConfigToJni and Java_im_zego_zegoexpress_internal_ZegoExpressEngineJniAPI_setEngineInitConfigToJni__Lim_zego_zegoexpress_entity_ZegoEngineConfig_2Ljava_lang_String_2JLjava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
2024-02-27 14:41:46.984 13177-13334 ReactNativeJS

**Comment by jackhmy** [comment]
do you load the libZegoExpressEngine.so file in the project?

**Comment by VikasReactNative** [comment]
node_modules/zego-express-engine-reactnative/android/build.gradle
android{
sourceSets { main { jniLibs.srcDirs = ['libs'] } } --need to add this
}
